name: Deploy Slides to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy slides to GitHub Pages
        run: |
          git push origin `git subtree split --prefix=slide/site master`:gh-pages --force